# Generated by Django 4.0 on 2021-12-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_category_gooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooditem',
            name='new_category',
            field=models.ManyToManyField(related_name='new_category', to='goods.Category'),
        ),
    ]
