# Generated by Django 4.0 on 2021-12-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('goods', '0004_gooditem_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooditem',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
